name: EnvTest

on:
  push:
    branches:
      - main
env:
  DAY_OF_WEEK: Monday
  
jobs:
  bash-example:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Group of log lines
        run: |
            echo "$Greeting Akhil. Today is $DAY_OF_WEEK"
