name: EnvTest

on:
  push:
    branches:
      - main
env:
  DAY_OF_WEEK: Monday
  
jobs:
  bash-example:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Group of log lines
        id: check-secrets
        run: |
            echo "$Greeting $First_Name Today is $DAY_OF_WEEK"
        env:
          First_Name: Mona
