name: EnvTest

on:
  push:
    branches:
      - main
jobs:
  bash-example:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Group of log lines
        run: |
            echo "$Greeting Akhil"
